Repository pivotal-cf/pcf-release-notes, pull requests merged in 2019-09, with the labels that each got.

#216 Add Autoscaler Known Issue
  runtime-rn.html.md.erb
Labels: scheduled

#215 Add Apps Manager release notes for PAS 2.7.0-rc.2
  runtime-rn.html.md.erb
Labels: scheduled

#217 Added missing Autoscaler Known Issue for PAS 2.7.0
  runtime-rn.html.md.erb
Labels: scheduled

#214 Add known issue for PWS logo
  runtime-rn.html.md.erb
Labels: scheduled

#213 Update known issues for custom logo
  runtime-rn.html.md.erb
Labels: scheduled

#218 Add known Loggregator issues to release notes
  runtime-rn.html.md.erb
Labels: scheduled

#223 Add Apps Manager release notes for PAS 2.3.18
  runtime-rn.html.md.erb
Labels: scheduled

#222 Add Apps Manager release notes for PAS 2.4.14
  runtime-rn.html.md.erb
Labels: scheduled

#221 Add Apps Manager release notes for PAS 2.5.10
  runtime-rn.html.md.erb
Labels: scheduled

#220 Add Apps Manager release notes for PAS 2.6.5
  runtime-rn.html.md.erb
Labels: scheduled

#219 Add Apps Manager release notes for PAS 2.7.0-rc.3
  runtime-rn.html.md.erb
Labels: scheduled

#224 Update Stale Routes Known Issue
  runtime-rn.html.md.erb
Labels: in progress

#229 Fix known issue about Apps Manager IE11 compatibility
  runtime-rn.html.md.erb
Labels: unscheduled

#228 Known issue for Apps Manager invitations failures
  runtime-rn.html.md.erb
Labels: unscheduled

#227 Known issue for Apps Manager invitations failures
  runtime-rn.html.md.erb
Labels: unscheduled

#226 Known issue for Apps Manager invitations failures
  runtime-rn.html.md.erb
Labels: unscheduled

#230 Known issue for Apps Manager invitations failures
  runtime-rn.html.md.erb
Labels: unscheduled
