Repository pivotal-cf/pcf-release-notes, pull requests merged in 2019-11, with the labels that each got.

#240 revisions to cover SCS v2.1.x
  breaking-changes.html.md.erb
Labels: scheduled

#241 Add Apps Manager release notes for PAS 2.7.3
  runtime-rn.html.md.erb
Labels: scheduled

#242 Add Apps Manager release notes for PAS 2.6.9
  runtime-rn.html.md.erb
Labels: scheduled

#243 Add Apps Manager release notes for PAS 2.5.14
  runtime-rn.html.md.erb
Labels: scheduled

#244 Add Apps Manager release notes for PAS 2.8.0-beta.1
  runtime-rn.html.md.erb
Labels: scheduled

#248 Add known issue for CredHub encryption password 2.5
  runtime-rn.html.md.erb
Labels: scheduled

#247 Add known issue for CredHub encryption password 2.4
  runtime-rn.html.md.erb
Labels: scheduled

#246 Fix anchor linking with unique ID
  runtime-rn.html.md.erb
Labels: in progress

#245 Add bug fix comment for OM 2.7.4
  opsmanager-rn.html.md.erb
Labels: scheduled

#251 Add bugfix to 2.7.1
  runtime-rn.html.md.erb
Labels: unscheduled

#250 Add bugfix to 2.6.7
  runtime-rn.html.md.erb
Labels: unscheduled

#249 Add bugfix to 2.5.12
  runtime-rn.html.md.erb
Labels: unscheduled
