Repository pivotal-cf/pcf-release-notes, pull requests merged in 2019-08, with the labels that each got.

#194 Apps Manager Custom Logo Whitelabeling Known Issue
  runtime-rn.html.md.erb
Labels: scheduled

#193 Apps Manager IE11 known issue
  runtime-rn.html.md.erb
Labels: scheduled

#192 Apps Manager IE11 known issue
  runtime-rn.html.md.erb
Labels: scheduled

#191 Apps Manager IE11 known issue
  runtime-rn.html.md.erb
Labels: scheduled

#190 Apps Manager IE11 known issue
  runtime-rn.html.md.erb
Labels: scheduled

#197 Add Apps Manager release notes for PAS 2.5.8
  runtime-rn.html.md.erb
Labels: scheduled

#198 Add Apps Manager release notes to PAS 2.6.3
  runtime-rn.html.md.erb
Labels: scheduled

#196 Add Apps Manager release notes for PAS 2.4.12
  runtime-rn.html.md.erb
Labels: scheduled

#195 Add Apps Manager release notes for PAS 2.3.16
  runtime-rn.html.md.erb
Labels: scheduled

#201 Add known issue about Apps Manager's Spring Boot Mappings
  runtime-rn.html.md.erb
Labels: unscheduled

#202 Add known issue about Apps Manager's Spring Boot Mappings
  runtime-rn.html.md.erb
Labels: unscheduled

#203 Add known issue about Apps Manager's Spring Boot Mappings
  runtime-rn.html.md.erb
Labels: unscheduled

#199 Add release notes for PASW Envoy-Nginx beta feature.
  windows-rn.html.md.erb
Labels: scheduled

#204 Specify where the new CA will be created
  opsmanager-rn.html.md.erb
Labels: in progress

#205 Added Visual C++ Redistributable Note
  windows-rn.html.md.erb
Labels: scheduled

#207 Updated to include back-ported visual c++ feature
  windows-rn.html.md.erb
Labels: scheduled

#206 Updated to include backported Visual C++ feature
  windows-rn.html.md.erb
Labels: scheduled

#208 Add Apps Manager release notes for PAS 2.4.13
  runtime-rn.html.md.erb
Labels: scheduled

#209 Add Apps Manager Release Notes for PAS 2.5.9
  runtime-rn.html.md.erb
Labels: in progress

#210 Add Apps Manager release notes for PAS 2.6.4
  runtime-rn.html.md.erb
Labels: scheduled

#211 Add Apps Manager release notes for PAS 2.7.0-rc.1
  runtime-rn.html.md.erb
Labels: in progress
