Repository pivotal-cf/pcf-release-notes, pull requests merged in 2020-07, with the labels that each got.

#322 Remove duplicated fix
  runtime-rn.html.md.erb
Labels: unscheduled

#323 Update Ops Manager 2.8.10 release notes
  opsmanager-rn.html.md.erb
Labels: in progress

#325 Update runtime-rn.html.md.erb
  runtime-rn.html.md.erb
Labels: unscheduled

#326 Update runtime-rn.html.md.erb
  runtime-rn.html.md.erb
Labels: scheduled

#327 Add release notes for routing 0.202.0 for TAS 2.7
  runtime-rn.html.md.erb
Labels: in progress

#328 Add release notes for routing 0.202.0 for TAS 2.8
  runtime-rn.html.md.erb
Labels: in progress

#329 Add release notes for routing 0.202.0 for TAS 2.9
  runtime-rn.html.md.erb
Labels: in progress

#330 Add patch version that resolve OM 2.7 known issue
  opsmanager-rn.html.md.erb
Labels: unscheduled
